import { Zone } from "../types/zone";

export const mockZones: Zone[] = [
  {
    id: "sto-101",
    name: "Zon 101 (Citygarage)",
    operator: "Aimo Park",
    city: "Stockholm",
    coords: { lat: 59.3315, lng: 18.0649 },
    capacity: 120,
    free: 14,
    pricing: { perHour: 45 },
    type: "garage",
    supports: { ev: true, disabled: true },
  },
  {
    id: "sto-102",
    name: "Zon 102 (Kungsgatan)",
    operator: "Stockholm Parkering",
    city: "Stockholm",
    coords: { lat: 59.3342, lng: 18.0601 },
    capacity: 28,
    free: 3,
    pricing: { perHour: 35 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "sto-103",
    name: "Zon 103 (Sergels torg)",
    operator: "Apcoa",
    city: "Stockholm",
    coords: { lat: 59.3327, lng: 18.0637 },
    capacity: 60,
    free: 0,
    pricing: { perHour: 55, note: "Hög taxa kväll" },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "sto-104",
    name: "Zon 104 (Vasastan)",
    operator: "Parkman",
    city: "Stockholm",
    coords: { lat: 59.3463, lng: 18.0529 },
    capacity: 18,
    free: 6,
    pricing: { perHour: 30 },
    type: "street",
    supports: { wide: true },
  },
  {
    id: "sto-105",
    name: "Zon 105 (P-skiva Odenplan)",
    operator: "Kommunal",
    city: "Stockholm",
    coords: { lat: 59.3422, lng: 18.0495 },
    capacity: 40,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "sto-106",
    name: "Zon 106 (Södermalm Hornsgatan)",
    operator: "Stockholm Parkering",
    city: "Stockholm",
    coords: { lat: 59.3176, lng: 18.0567 },
    capacity: 26,
    free: 8,
    pricing: { perHour: 28 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "sto-107",
    name: "Zon 107 (Norrmalm T-Centralen)",
    operator: "Apcoa",
    city: "Stockholm",
    coords: { lat: 59.3309, lng: 18.0597 },
    capacity: 140,
    free: 5,
    pricing: { perHour: 60 },
    type: "garage",
    supports: { ev: true, wide: true },
  },
  {
    id: "sto-108",
    name: "Zon 108 (Djurgården)",
    operator: "Aimo Park",
    city: "Stockholm",
    coords: { lat: 59.327, lng: 18.1066 },
    capacity: 50,
    free: 12,
    pricing: { perHour: 35 },
    type: "street",
    supports: {},
  },
  {
    id: "sto-109",
    name: "Zon 109 (Solna Centrum)",
    operator: "Parkman",
    city: "Stockholm",
    coords: { lat: 59.3601, lng: 18.0018 },
    capacity: 90,
    free: 2,
    pricing: { perHour: 32 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "sto-110",
    name: "Zon 110 (Brommaplan)",
    operator: "Kommunal",
    city: "Stockholm",
    coords: { lat: 59.3387, lng: 17.9397 },
    capacity: 22,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "got-201",
    name: "Zon 201 (Nordstan)",
    operator: "Göteborgs Stads Parkering",
    city: "Göteborg",
    coords: { lat: 57.7089, lng: 11.9687 },
    capacity: 150,
    free: 9,
    pricing: { perHour: 32 },
    type: "garage",
    supports: { ev: true, disabled: true },
  },
  {
    id: "got-202",
    name: "Zon 202 (Avenyn)",
    operator: "Aimo Park",
    city: "Göteborg",
    coords: { lat: 57.7019, lng: 11.9746 },
    capacity: 34,
    free: 2,
    pricing: { perHour: 28 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "got-203",
    name: "Zon 203 (Liseberg)",
    operator: "Apcoa",
    city: "Göteborg",
    coords: { lat: 57.6953, lng: 11.9912 },
    capacity: 90,
    free: 0,
    pricing: { perHour: 40 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "got-204",
    name: "Zon 204 (Haga)",
    operator: "Parkman",
    city: "Göteborg",
    coords: { lat: 57.6997, lng: 11.9543 },
    capacity: 22,
    free: 7,
    pricing: { perHour: 24 },
    type: "street",
    supports: { wide: true },
  },
  {
    id: "got-205",
    name: "Zon 205 (Gratis Linné)",
    operator: "Kommunal",
    city: "Göteborg",
    coords: { lat: 57.6958, lng: 11.9548 },
    capacity: 30,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "got-206",
    name: "Zon 206 (Lindholmen)",
    operator: "Aimo Park",
    city: "Göteborg",
    coords: { lat: 57.7066, lng: 11.9389 },
    capacity: 70,
    free: 10,
    pricing: { perHour: 26 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "got-207",
    name: "Zon 207 (Järntorget)",
    operator: "Göteborgs Stads Parkering",
    city: "Göteborg",
    coords: { lat: 57.7009, lng: 11.9529 },
    capacity: 30,
    free: 3,
    pricing: { perHour: 22 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "got-208",
    name: "Zon 208 (Ullevi)",
    operator: "Apcoa",
    city: "Göteborg",
    coords: { lat: 57.7082, lng: 11.9862 },
    capacity: 120,
    free: 0,
    pricing: { perHour: 38 },
    type: "garage",
    supports: { ev: true, wide: true },
  },
  {
    id: "got-209",
    name: "Zon 209 (Majorna)",
    operator: "Parkman",
    city: "Göteborg",
    coords: { lat: 57.6951, lng: 11.9275 },
    capacity: 18,
    free: 6,
    pricing: { perHour: 20 },
    type: "street",
    supports: {},
  },
  {
    id: "got-210",
    name: "Zon 210 (Gratis Slottskogen)",
    operator: "Kommunal",
    city: "Göteborg",
    coords: { lat: 57.6895, lng: 11.9493 },
    capacity: 28,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "mal-301",
    name: "Zon 301 (Triangeln)",
    operator: "Malmö Stads Parkering",
    city: "Malmö",
    coords: { lat: 55.5944, lng: 13.0006 },
    capacity: 110,
    free: 11,
    pricing: { perHour: 25 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "mal-302",
    name: "Zon 302 (Möllevången)",
    operator: "Aimo Park",
    city: "Malmö",
    coords: { lat: 55.5908, lng: 13.0132 },
    capacity: 26,
    free: 4,
    pricing: { perHour: 20 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "mal-303",
    name: "Zon 303 (Västra Hamnen)",
    operator: "Apcoa",
    city: "Malmö",
    coords: { lat: 55.6079, lng: 12.9777 },
    capacity: 70,
    free: 1,
    pricing: { perHour: 30 },
    type: "garage",
    supports: { ev: true, wide: true },
  },
  {
    id: "mal-304",
    name: "Zon 304 (Centralen)",
    operator: "Parkman",
    city: "Malmö",
    coords: { lat: 55.6097, lng: 13.0022 },
    capacity: 20,
    free: 6,
    pricing: { perHour: 24 },
    type: "street",
    supports: {},
  },
  {
    id: "mal-305",
    name: "Zon 305 (Gratis Pildammarna)",
    operator: "Kommunal",
    city: "Malmö",
    coords: { lat: 55.5916, lng: 12.9882 },
    capacity: 36,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "mal-306",
    name: "Zon 306 (Hyllie Station)",
    operator: "Malmö Stads Parkering",
    city: "Malmö",
    coords: { lat: 55.5659, lng: 12.9766 },
    capacity: 130,
    free: 15,
    pricing: { perHour: 24 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "mal-307",
    name: "Zon 307 (Folkets Park)",
    operator: "Aimo Park",
    city: "Malmö",
    coords: { lat: 55.5923, lng: 13.0237 },
    capacity: 22,
    free: 4,
    pricing: { perHour: 20 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "mal-308",
    name: "Zon 308 (Emporia)",
    operator: "Apcoa",
    city: "Malmö",
    coords: { lat: 55.5679, lng: 12.9711 },
    capacity: 180,
    free: 7,
    pricing: { perHour: 28 },
    type: "garage",
    supports: { ev: true, wide: true },
  },
  {
    id: "mal-309",
    name: "Zon 309 (Gamla Väster)",
    operator: "Parkman",
    city: "Malmö",
    coords: { lat: 55.6056, lng: 12.9948 },
    capacity: 16,
    free: 6,
    pricing: { perHour: 22 },
    type: "street",
    supports: {},
  },
  {
    id: "mal-310",
    name: "Zon 310 (Gratis Ribersborg)",
    operator: "Kommunal",
    city: "Malmö",
    coords: { lat: 55.6025, lng: 12.9695 },
    capacity: 26,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "upp-401",
    name: "Zon 401 (Resecentrum)",
    operator: "Uppsala Parkering",
    city: "Uppsala",
    coords: { lat: 59.8586, lng: 17.6467 },
    capacity: 80,
    free: 8,
    pricing: { perHour: 22 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "upp-402",
    name: "Zon 402 (Stora torget)",
    operator: "Kommunal",
    city: "Uppsala",
    coords: { lat: 59.8581, lng: 17.6393 },
    capacity: 18,
    free: 5,
    pricing: { perHour: 18 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "upp-403",
    name: "Zon 403 (Akademiska)",
    operator: "Aimo Park",
    city: "Uppsala",
    coords: { lat: 59.8567, lng: 17.6301 },
    capacity: 45,
    free: 0,
    pricing: { perHour: 26 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "upp-404",
    name: "Zon 404 (Luthagen)",
    operator: "Parkman",
    city: "Uppsala",
    coords: { lat: 59.8652, lng: 17.6282 },
    capacity: 16,
    free: 9,
    pricing: { perHour: 16 },
    type: "street",
    supports: { wide: true },
  },
  {
    id: "upp-405",
    name: "Zon 405 (Gratis Fyrisån)",
    operator: "Kommunal",
    city: "Uppsala",
    coords: { lat: 59.8596, lng: 17.6501 },
    capacity: 25,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "upp-406",
    name: "Zon 406 (Gränby Centrum)",
    operator: "Uppsala Parkering",
    city: "Uppsala",
    coords: { lat: 59.8792, lng: 17.6732 },
    capacity: 90,
    free: 9,
    pricing: { perHour: 20 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "upp-407",
    name: "Zon 407 (Svartbäcken)",
    operator: "Parkman",
    city: "Uppsala",
    coords: { lat: 59.8684, lng: 17.6355 },
    capacity: 18,
    free: 3,
    pricing: { perHour: 16 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "upp-408",
    name: "Zon 408 (Boländerna)",
    operator: "Apcoa",
    city: "Uppsala",
    coords: { lat: 59.8469, lng: 17.6746 },
    capacity: 120,
    free: 0,
    pricing: { perHour: 24 },
    type: "garage",
    supports: { ev: true, wide: true },
  },
  {
    id: "upp-409",
    name: "Zon 409 (Flogsta)",
    operator: "Aimo Park",
    city: "Uppsala",
    coords: { lat: 59.8447, lng: 17.6036 },
    capacity: 24,
    free: 7,
    pricing: { perHour: 18 },
    type: "street",
    supports: {},
  },
  {
    id: "upp-410",
    name: "Zon 410 (Gratis Studenternas)",
    operator: "Kommunal",
    city: "Uppsala",
    coords: { lat: 59.8493, lng: 17.6384 },
    capacity: 20,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
  {
    id: "lin-501",
    name: "Zon 501 (Resecentrum)",
    operator: "Linköpings Kommun",
    city: "Linköping",
    coords: { lat: 58.4115, lng: 15.6233 },
    capacity: 65,
    free: 12,
    pricing: { perHour: 20 },
    type: "garage",
    supports: { ev: true },
  },
  {
    id: "lin-502",
    name: "Zon 502 (Storgatan)",
    operator: "Parkman",
    city: "Linköping",
    coords: { lat: 58.4096, lng: 15.6249 },
    capacity: 20,
    free: 4,
    pricing: { perHour: 16 },
    type: "street",
    supports: { disabled: true },
  },
  {
    id: "lin-503",
    name: "Zon 503 (US Universitetssjukhus)",
    operator: "Aimo Park",
    city: "Linköping",
    coords: { lat: 58.4108, lng: 15.6211 },
    capacity: 48,
    free: 0,
    pricing: { perHour: 24 },
    type: "garage",
    supports: { ev: true, wide: true },
  },
  {
    id: "lin-504",
    name: "Zon 504 (Trädgårdstorget)",
    operator: "Kommunal",
    city: "Linköping",
    coords: { lat: 58.4091, lng: 15.6267 },
    capacity: 14,
    free: 6,
    pricing: { perHour: 14 },
    type: "street",
    supports: {},
  },
  {
    id: "lin-505",
    name: "Zon 505 (Gratis Stångebro)",
    operator: "Kommunal",
    city: "Linköping",
    coords: { lat: 58.4092, lng: 15.6351 },
    capacity: 22,
    free: null,
    pricing: { perHour: null, note: "Gratis / P-skiva" },
    type: "free",
    supports: {},
  },
];

export const fetchZones = async () => {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return mockZones;
};

export const tickAvailability = (zones: Zone[]) =>
  zones.map((zone) => {
    if (zone.free === null) {
      return zone;
    }
    const delta = Math.floor(Math.random() * 3) - 1;
    const next = Math.min(zone.capacity, Math.max(0, zone.free + delta));
    return { ...zone, free: next };
  });
